### ISSUE TITLE
Publish this as a package to PyPI

### ISSUE THREAD

**Issue by themoosman** [Benehiko/ReolinkCameraAPI#17]
Before I submit the PR, do you have any objections to publishing this great work to PyPi as a package?

**Comment by Benehiko** [comment]
No objection at all! :smile:

**Comment by themoosman** [comment]
Do you want to do to the initial release?

**Comment by Benehiko** [comment]
I have done so :)
Thank you for contributing - it's really appreciated 
https://pypi.org/project/reolink-api/0.0.1/

**Comment by themoosman** [comment]
Boom!  Thank you for starting the project.
