### ISSUE TITLE
Any support for PTZ

### ISSUE THREAD

**Issue by strunker** [Benehiko/ReolinkCameraAPI#24]
Is there anyway to control PTZ with the API? I am coming from Foscam which has a super rich rest api where you can control motion detection, alarm settings, PTZ, and move the camera to specific positions, etc.  thanks

**Comment by themoosman** [comment]
Yes.

https://github.com/Benehiko/ReolinkCameraAPI/blob/master/api/ptz.py

**Comment by strunker** [comment]
Very cool :) Thanks for the fast reply.
