### ISSUE TITLE
API/Camera Question

### ISSUE THREAD

**Issue by JoshChristie** [Benehiko/ReolinkCameraAPI#4]
Hi,
Nice package! Just wondering if you run into any limitations/issues with the API so far. I'm looking in to getting a wifi/ip camera and would like to control all it's parameters. 

Did you run into the same issue as here?
https://ipcamtalk.com/threads/control-reolink-rlc-423-with-api.16815/

Thanks

**Comment by Benehiko** [comment]
Well, the API in this package is based on their web-client API calls and still a work-in-progress. I still have a while to go to implement support for other cameras other than the [RLC-411W](https://reolink.com/product/rlc-411/). The limitations will thus be based on what their web-client supports (theoretically). I have not found a limitation per se with what I have implemented currently.
